checks:
  php: true

build:
  environment:
    php:
      version: '8.2'
      ini:
        xdebug.mode: coverage
  tests:
    override:
      - php-scrutinizer-run
      -
        command: 'vendor/bin/phpunit --coverage-clover=psfs-coverage'
        coverage:
          file: 'psfs-coverage'
          format: 'clover'

filter:
  excluded_paths:
    - src/bin/*
    - src/command/*
    - src/tests/*
    - src/public/*
    - src/templates/*
    - locale/*
    - cache/*
    - config/*
    - logs/*
    - vendor/*
