filter:
  excluded_paths:
    - src/bin/*
    - src/command/*
    - src/tests/*
    - src/public/*
    - src/templates/*
    - locale/*
    - cache/*
    - config/*
    - logs/*
    - tests/*
    - tests_api/*
  dependency_paths:
    - vendor/

checks:
    php: true

build:
  environment:
    php:
      version: "8.2.0"
  dependencies:
    override:
      - true
  project_setup:
    override:
      - true
  tests:
    override:
      - true
  nodes:
    docker-tests:
      environment:
        docker: true
        variables:
          APP_ENVIRONMENT: "test"
          HOST_PORT: "8008"
          DEBUG: "-xdebug"
          PHP_OPCACHE: "0"
      dependencies:
        override:
          - true
      project_setup:
        override:
          - true
      tests:
        stop_on_failure: true
        override:
          - command: "bash tools/ci/scrutinizer-docker-tests.sh"
            coverage:
              file: "cache/coverage/coverage.xml"
              format: "clover"
