filter:
  paths:
    - "src/*"
    - "tests/*"
  excluded_paths:
    - src/bin/*
    - src/command/*
    - src/tests/*
    - src/public/*
    - src/templates/*
    - locale/*
    - cache/*
    - config/*
    - logs/*
    - vendor/*

build_failure_conditions:
  - "issues.severity(>= MAJOR).new.exists"
  - "project.metric('scrutinizer.test_coverage', < 0.70)"

build:
  environment:
    php:
      version: 8.2
      ini:
        memory_limit: "-1"
        pecl_extensions:
          - zip
          - intl
          - curl
          - gmp
    variables:
      APP_ENV: "scrutinizer"
  nodes:
    analysis:
      tests:
        override:
          - "php-scrutinizer-run"
    tests:
      dependencies:
        before:
          - "composer install --no-interaction --prefer-dist --no-progress"
      tests:
        override:
          - "vendor/bin/phpunit --configuration phpunit.xml"
      coverage:
        file: "build/logs/clover.xml"
        format: "clover"