filter:
  excluded_paths:
    - src/bin/*
    - src/command/*
    - src/tests/*
    - src/public/*
    - src/templates/*
    - locale/*
    - cache/*
    - config/*
    - logs/*
    - tests/*
  dependency_paths:
    - vendor/

checks:
    php: true

build:
  environment:
    timezone: "Europe/Madrid"
    php:
      version: 8.2
      ini:
        memory_limit: "-1"
        xdebug.mode: coverage
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis
    coverage:
      dependencies:
        before:
          - "composer install -o --no-interaction --no-progress"
      tests:
        override:
          - command: "vendor/bin/phpunit --configuration phpunit.xml.dist"
            coverage:
              file: "cache/coverage/coverage.xml"
              format: "clover"