version: '3.3'

services:
  php:
    image: stratecode/php:${PHP_VERSION:-8.3}${DEBUG:-}
    working_dir: /var/www
    command: sleep 86400
    environment:
      XDEBUG_MODE: coverage
      PHP_TIMEZONE: Europe/Madrid
      PHP_OPCACHE: '0'
    depends_on:
      - redis

  redis:
    image: valkey/valkey:latest
    command: ["valkey-server", "--appendonly", "no", "--save", ""]

  db:
    image: mysql:8.4
    environment:
      MYSQL_USER: psfs
      MYSQL_PASSWORD: psfs
      MYSQL_ROOT_PASSWORD: psfs
      MYSQL_DATABASE: psfs
