version: '3.3'

services:
  php:
    image: stratecode/php:${PHP_VERSION:-8.3}${DEBUG:-}
    volumes:
      - .:/var/www
      - ./docker/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www
    command: php -S 0.0.0.0:8080 -t ./html
    depends_on:
      - redis

  redis:
    image: valkey/valkey:latest
    command: ["valkey-server", "--appendonly", "no", "--save", ""]

  db:
    image: mysql:8.4
    environment:
      MYSQL_USER: psfs
      MYSQL_PASSWORD: psfs
      MYSQL_ROOT_PASSWORD: psfs
      MYSQL_DATABASE: psfs
