<?php

namespace PSFS\base\config;

use PSFS\base\exception\ConfigException;
use PSFS\base\Logger;
use PSFS\base\Request;
use PSFS\base\Security;
use PSFS\base\types\helpers\Inspector;
use PSFS\base\types\traits\SingletonTrait;
use PSFS\base\types\traits\TestTrait;

/**
 * @package PSFS\base\config
 */
class Config
{
    use SingletonTrait;
    use TestTrait;

    const DEFAULT_LANGUAGE = 'en';
    const DEFAULT_ENCODE = 'UTF-8';
    const DEFAULT_CTYPE = 'text/html';
    const DEFAULT_DATETIMEZONE = 'Europe/Madrid';

    const CONFIG_FILE = 'config.json';
    const CONFIG_CACHE_TTL = 60;

    protected array $config = [];
    protected ConfigRepositoryInterface $repository;
    static public array $defaults = [
        'db.host' => 'localhost',
        'db.port' => '3306',
        'default.language' => 'en_US',
        'debug' => true,
        'front.version' => 'v1',
        'version' => 'v1',
    ];
    static public array $required = [
        'db.host',
        'db.port',
        'db.name',
        'db.user',
        'db.password',
        'home.action',
        'default.language',
        'debug'
    ];
    static public array $encrypted = ['db.password'];
    static public array $optional = [
        'platform.name', // Platform name
        'restricted', // Restrict the web access
        'admin.login', // Enable web login for admin
        'logger.phpFire', // Enable phpFire to trace the logs in the browser
        'logger.memory', // Enable log memory usage un traces
        'poweredBy', // Show PoweredBy header customized
        'author', // Author for auto generated files
        'author.email', // Author email for auto generated files
        'version', // Platform version(for cache purposes)
        'front.version', // Static resources version
        'cors.enabled', // Enable CORS (regex with the domains, * for all)
        'pagination.limit', // Pagination limit for autogenerated api admin
        'api.secret', // Secret passphrase to securize the api
        'api.admin', // Enable the autogenerated api admin(wok)
        'log.level', // Max log level(default INFO)
        'admin_action', // Default admin url when access to /admin
        'cache.var', // Static cache var
        'twig.autoreload', // Enable or disable auto reload templates for twig
        'modules.extend', // Variable for extending the current functionality
        'psfs.auth', // Variable for extending PSFS with the AUTH module
        'errors.strict', // Variable to trace all strict errors
        'psfs.memcache', // Add Memcache to prod cache process, ONLY for PROD environments
        'angular.protection', // Add an angular suggested prefix in order to avoid JSONP injections
        'cors.headers', // Add extra headers to the CORS check
        'json.encodeUTF8', // Encode the json response
        'cache.data.enable', // Enable data caching with PSFS
        'profiling.enable', // Enable the profiling headers
        'api.extrafields.compat', // Disbale retro compatibility with extra field mapping in api
        'output.json.strict_numbers', // Enable strict numbers in json responses
        'admin.version', // Determines the version for the admin ui
        'api.block.limit', // Determine the number of rows for bulk insert
        'api.field.types', // Extract __fields from api with their types
        'api.version', // API version exposed in generated API documentation
        'i18n.locales', // Default locales for any project
        'log.slack.hook', // Hook for slack traces
        'i18n.autogenerate', // Set PSFS auto generate i18n mode
        'default.locale', // Default locale used for generated module structure
        'resources.cdn.url', // CDN URL base path
        'api.field.case', // Field type for API dtos (phpName|camelName|camelName|fieldName) @see Propel TableMap class
        'route.404', // Set route for 404 pages
        'project.timezone', // Set the timezone for the timestamps in PSFS(Europe/madrid by default)
        'curl.returnTransfer', // Curl option CURLOPT_RETURNTRANSFER
        'curl.followLocation', // Curl option CURLOPT_FOLLOWLOCATION
        'curl.connectTimeout', // Curl option CURLOPT_CONNECTTIMEOUT
        'curl.timeout', // Curl option CURLOPT_TIMEOUT
        'curl.sslVerifyHost', // Curl option CURLOPT_SSL_VERIFYHOST
        'curl.sslVerifyPeer', // Curl option CURLOPT_SSL_VERIFYPEER
        'assets.obfuscate', // Allow to obfuscate and gzip js and css files
        'allow.double.slashes', // Allow // in url paths, allowed as default
        'default.log.path', // Default logger path
        'force.https', // Force https protocol for static resources
        'hide.modules', // Hide modules from menu, separated by comma
        'skip.route_generation', // Skip routes generation
        'auth.expiration', // Set the expiration time for the auth token
        'api.query_token.compat', // Allow legacy API_TOKEN query string fallback (deprecated)
        'api.token.cookie', // Cookie name for API token fallback
        'enable.jwt', // Enable JWT auth flow fallback/compat in security checks
        'jwt.alg', // JWT signing/verification algorithm
        'jwt.expiration_seconds', // JWT token expiration in seconds
        'csrf.expiration', // CSRF token expiration time (seconds)
        'db.log.max_files', // Max rotated files for DB-related logs in generated Propel config
        'psfs.redis', // Enable redis read-through cache
        'cache.config.ttl', // Config read-through ttl
        'cache.reflections.ttl', // Reflection cache read-through ttl
        'redis.host', // Redis host for read-through caches
        'redis.port', // Redis port for read-through caches
        'redis.timeout', // Redis timeout for read-through caches
        'job.queue.redis.prefix', // Redis key prefix for PSFS async queue subsystem
        'metadata.attributes.enabled', // Enable php attributes metadata extraction
        'i18n.provider.custom.enabled', // Use custom provider before gettext
        'i18n.missing.report.path', // Path where missing i18n keys will be reported
    ];
    protected bool $debug = false;
    public static array $cleanable_config_files = ['domains.json', 'urls.json'];

    /**
     * @return Config
     */
    protected function init()
    {
        $this->repository = $this->createRepository();
        if (file_exists($this->repository->getConfigPath())) {
            $this->loadConfigData();
        }
        return $this;
    }

    /**
     * @return bool
     */
    public function isLoaded()
    {
        return !empty($this->config);
    }

    /**
     * @param array $data
     * @param array $extra
     * @return array
     */
    protected static function saveConfigParams(array $data, $extra = null)
    {
        Logger::log('Saving required config parameters');
        // Store newly provided configuration parameters.
        if (!empty($extra) && array_key_exists('label', $extra) && is_array($extra['label'])) {
            foreach ($extra['label'] as $index => $field) {
                if (array_key_exists($index, $extra['value']) && !empty($extra['value'][$index])) {
                    $data[$field] = $extra['value'][$index];
                }
            }
        }
        return $data;
    }

    /**
     * @param array $data
     * @return array
     */
    protected static function saveExtraParams(array $data)
    {
        $finalData = array();
        if (!empty($data)) {
            Logger::log('Saving extra configuration parameters');
            foreach (self::iterateConfigEntries($data) as [$key, $value]) {
                if (null !== $value) {
                    $finalData[$key] = $value;
                }
            }
        }
        return $finalData;
    }

    /**
     * @return boolean
     */
    public function getDebugMode()
    {
        return $this->debug;
    }

    /**
     * @param bool $debug
     */
    public function setDebugMode($debug = true)
    {
        $this->debug = $debug;
        $this->config['debug'] = $this->debug;
    }

    /**
     * @return boolean
     */
    public function isConfigured()
    {
        Inspector::stats('[Config] Checking configuration', Inspector::SCOPE_DEBUG);
        $configured = !empty($this->config);
        if ($configured) {
            foreach (static::$required as $required) {
                if (!array_key_exists($required, $this->config)) {
                    $configured = false;
                    break;
                }
            }
        }
        return $configured || $this->checkTryToSaveConfig() || self::isTest();
    }

    /**
     * @return bool
     */
    public function checkTryToSaveConfig()
    {
        $uri = Request::getInstance()->getRequestUri();
        $method = Request::getInstance()->getMethod();
        return (preg_match('/^\/admin\/(config|setup)$/', $uri) === 1 && strtoupper($method) === 'POST');
    }

    /**
     *
     * @param array $data
     * @param array|null $extra
     * @return boolean
     */
    public static function save(array $data, $extra = null)
    {
        $data = self::saveConfigParams($data, $extra);
        $finalData = self::saveExtraParams($data);
        $saved = false;
        try {
            $finalData = array_filter($finalData, function ($key, $value) {
                return in_array($key, self::$required, true) || !empty($value);
            }, ARRAY_FILTER_USE_BOTH);
            ksort($finalData, SORT_NATURAL | SORT_FLAG_CASE);
            $instance = self::getInstance();
            $saved = $instance->repository->save($finalData);
            $instance->loadConfigData(true);
        } catch (ConfigException $e) {
            Logger::log($e->getMessage(), LOG_ERR);
        }
        return $saved;
    }

    /**
     * @param string $param
     * @param mixed|null $defaultValue
     *
     * @return mixed|null
     */
    public function get($param, $defaultValue = null)
    {
        return array_key_exists($param, $this->config) ? $this->config[$param] : $defaultValue;
    }

    /**
     * @return array
     */
    public function dumpConfig(): array
    {
        return $this->config ?: [];
    }


    public function loadConfigData(bool $refresh = false): void
    {
        $this->config = $refresh ? $this->repository->refresh() : $this->repository->read();
        $this->debug = array_key_exists('debug', $this->config) ? (bool)$this->config['debug'] : false;
        if (array_key_exists('cache.var', $this->config)) {
            Security::getInstance()->setSessionKey('config.cache.var', $this->config['cache.var']);
        }
    }


    public function clearConfig()
    {
        $this->config = [];
    }

    /**
     * @param string $key
     * @param mixed|null $defaultValue
     * @param string|null $module
     * @return mixed|null
     */
    public static function getParam($key, $defaultValue = null, $module = null)
    {
        if (null !== $module) {
            return self::getParam(strtolower($module) . '.' . $key, self::getParam($key, $defaultValue));
        }
        $param = self::getInstance()->get($key);
        return (null !== $param) ? $param : $defaultValue;
    }

    public static function initialize(): void
    {
        Config::getInstance();
        Logger::getInstance();
    }

    public static function clearConfigFiles(): bool
    {
        $done = true;
        foreach (self::$cleanable_config_files as $configFile) {
            if (file_exists(CONFIG_DIR . DIRECTORY_SEPARATOR . $configFile)) {
                if (!unlink(CONFIG_DIR . DIRECTORY_SEPARATOR . $configFile)) {
                    $done = false;
                }
            }
        }
        return $done;
    }

    protected function createRepository(): ConfigRepositoryInterface
    {
        $configPath = CONFIG_DIR . DIRECTORY_SEPARATOR . self::CONFIG_FILE;
        $fileRepository = new FileConfigRepository($configPath);
        $seed = $fileRepository->read();
        $redisEnabled = (bool)($seed['psfs.redis'] ?? false);
        if ($redisEnabled && class_exists(\Redis::class)) {
            $ttl = (int)($seed['cache.config.ttl'] ?? self::CONFIG_CACHE_TTL);
            $version = (string)($seed['cache.var'] ?? 'v1');
            return new RedisReadThroughConfigRepository($fileRepository, $ttl, $version);
        }
        return $fileRepository;
    }

    /**
     * @param array $data
     * @return \Generator
     */
    private static function iterateConfigEntries(array $data): \Generator
    {
        foreach ($data as $key => $value) {
            yield [$key, $value];
        }
    }
}
