<?php
namespace PSFS\base\types;

/**
 * Class CustomApi
 * @package PSFS\base\types
 */
abstract class CustomApi extends Api {

    public function getModelTableMap()
    {
        return null;
    }

    public function modelList()
    {
        return parent::modelList(); // TODO: Change the autogenerated stub
    }

    public function get($pk)
    {
        return null;
    }

    public function delete($pk = NULL)
    {
        return null;
    }

    public function post()
    {
        return null;
    }

    public function put($pk)
    {
        return null;
    }

    public function admin() {
        return null;
    }
}